In [3]:
import time
import tushare as ts

In [4]:
ts.set_token('aecca28adc0d5a7764b748ccd48bef923d81314ae47b4d44d51fce67')
tsp = ts.pro_api()
ts.__version__

'1.2.62'

In [62]:
df = tsp.stock_basic(fields='symbol,name,market,area,industry,list_date')
df

      symbol      name area industry market list_date
0     000001      平安银行   深圳       银行     主板  19910403
1     000002       万科A   深圳     全国地产     主板  19910129
2     000004      国华网安   深圳      互联网     主板  19910114
3     000005      世纪星源   深圳     环境保护     主板  19901210
4     000006      深振业A   深圳     区域地产     主板  19920427
...      ...       ...  ...      ...    ...       ...
4132  688699      明微电子   深圳      半导体    科创板  20201218
4133  688777      中控技术   浙江     软件服务    科创板  20201124
4134  688788      科思科技   深圳     通信设备    科创板  20201022
4135  688981    中芯国际-U   上海      半导体    科创板  20200716
4136  689009  九号公司-UWD   北京     专用机械    CDR  20201029

[4137 rows x 6 columns]

In [55]:
listed_symbols = df['symbol'].to_list()

In [56]:
today = time.strftime('%Y%m%d', time.localtime())
today

'20210114'

In [57]:
suspended_symbols = list([x[:6] for x in tsp.suspend_d(suspend_type='S', trade_date=today)['ts_code'].to_list()])

In [59]:
symbols = list([symbol for symbol in listed_symbols if symbol not in suspended_symbols])
len(symbols)

4126

In [30]:
df = tsp.query('suspend', ts_code='', suspend_date=today, resume_date='', fields='')
df

      ts_code suspend_date resume_date suspend_reason
0   601866.SH     20210114        None           重大事项
1   000996.SZ     20210114        None           重大事项
2   600086.SH     20210114        None         刊登重要公告
3   000780.SZ     20210114        None       筹划重大资产重组
4   000885.SZ     20210114        None       筹划重大资产重组
5   000826.SZ     20210114        None       筹划重大资产重组
6   002642.SZ     20210114        None           重大事项
7   300424.SZ     20210114        None           重大事项
8   600796.SH     20210114        None      拟筹划重大资产重组
9   300307.SZ     20210114        None        拟披露重大事项
10  000662.SZ     20210114        None           重大事项

In [31]:
df = tsp.suspend_d(suspend_type='S', trade_date=today)
df

      ts_code trade_date suspend_timing suspend_type
0   000662.SZ   20210114           None            S
1   000670.SZ   20210114           None            S
2   000760.SZ   20210114           None            S
3   000792.SZ   20210114           None            S
4   000939.SZ   20210114           None            S
5   002260.SZ   20210114           None            S
6   002359.SZ   20210114           None            S
7   002450.SZ   20210114           None            S
8   002604.SZ   20210114           None            S
9   002711.SZ   20210114           None            S
10  300028.SZ   20210114           None            S
11  300104.SZ   20210114           None            S
12  300216.SZ   20210114           None            S
13  300362.SZ   20210114           None            S
14  300431.SZ   20210114           None            S
15  600074.SH   20210114           None            S
16  600485.SH   20210114           None            S
17  600614.SH   20210114           None            S
18  600677.SH   20210114           None            S
19  600701.SH   20210114           None            S
20  600891.SH   20210114           None            S
21  601866.SH   20210114           None            S
22  000780.SZ   20210114           None            S
23  000826.SZ   20210114           None            S
24  000885.SZ   20210114           None            S
25  000996.SZ   20210114           None            S
26  002642.SZ   20210114           None            S
27  300307.SZ   20210114           None            S
28  300424.SZ   20210114           None            S
29  600086.SH   20210114           None            S
30  600796.SH   20210114           None            S

'20210114'